name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package \
          -DrepositoryId=github \
          -Durl="https://maven.pkg.github.com/GabrielCruzSoto/t2-auth-openapi" \
          -Dusername="${{ github.actor }}" \
          -Dpassword="${{ secrets.GITHUB_TOKEN }}"

      - name: Build Docker image
        run: docker build -t ghcr.io/gabrielcruzsoto/t2-excel-processor-api:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/gabrielcruzsoto/t2-excel-processor-api:latest
